### ISSUE TITLE
Build failures when compiling with  GHC 7.10.1 (cabal 1.22.3.0)

### ISSUE THREAD

**Issue by apauley** [simonmar/parconc-examples#12]
Hi Simon,

I experienced some issues when I tried to build this project with my Haskell versions (cabal 1.22.3.0 and GHC 7.10.1). The build was done on Mac OS X, although I don't think the OS played much of a role in this case.

I was able to fix most of these failures by relaxing the version requirements, see my commit for details:
https://github.com/apauley/parconc-examples/commit/771c4e579fe7c8c02af8297f3926fae068c83169

The executables that I could not fix with version number bumping are left commented out.
Would you like a pull request for the fixes in the commit above?

For completeness, below are the errors I initially received when attempting to follow the book instructions (in a clean sandbox) listed at http://chimera.labs.oreilly.com/books/1230000000929/ch01.html#sec_into-tools

The same errors are present when trying to compile from the git repository.

```
Iris:parconc andreas$ cabal unpack parconc-examples
Unpacking to parconc-examples-0.3.4/
Iris:parconc andreas$ cd parconc-examples-0.3.4
Iris:parconc-examples-0.3.4 andreas$ cabal sandbox init
Writing a default package environment file to
/Users/andreas/Code/Haskell/tmp/parconc/parconc-examples-0.3.4/cabal.sandbox.config
Creating a new sandbox at
/Users/andreas/Code/Haskell/tmp/parconc/parconc-examples-0.3.4/.cabal-sandbox
Iris:parconc-examples-0.3.4 andreas$ cabal install --only-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: parconc-examples-0.3.4 (user goal)
next goal: base (dependency of parconc-examples-0.3.4)
rejecting: base-4.8.0.0/installed-901... (conflict: parconc-examples =>
base>=4.5 && <4.8)
rejecting: base-4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0,
4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0,
4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed
instance)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by apauley** [comment]
I tested the build on Linux with GHC version 7.8.4 (cabal-install version 1.22.3.0).
The build also fails in this environment, but for different reasons (not related to dependency version numbers).
The executables that fail to compile include parinfer, Async, TList, TQueue, TBQueue and tmvar.
See below for an example failure with parinfer.

My commit with the relaxed version dependencies (apauley@771c4e5) builds successfully in this environment, although it did not fix the issues above:
the relevant executables were just disabled in the cabal file due to also causing build failures on GHC 7.10.1

```
parinfer/InferMonad.hs:63:10: Warning:
    ‘Infer’ is an instance of Monad but not Applicative - this will become an error in GHC 7.10, under the Applicative-Monad Proposal.
[ 9 of 14] Compiling Term             ( parinfer/Term.hs, dist/dist-sandbox-89d2cce8/build/parinfer/parinfer-tmp/Term.o )
[10 of 14] Compiling Environment      ( parinfer/Environment.hs, dist/dist-sandbox-89d2cce8/build/parinfer/parinfer-tmp/Environment.o )
[11 of 14] Compiling Infer            ( parinfer/Infer.hs, dist/dist-sandbox-89d2cce8/build/parinfer/parinfer-tmp/Infer.o )
[12 of 14] Compiling Lex              ( dist/dist-sandbox-89d2cce8/build/parinfer/parinfer-tmp/Lex.hs, dist/dist-sandbox-89d2cce8/build/parinfer/parinfer-tmp/Lex.o )

dist/dist-sandbox-89d2cce8/build/parinfer/parinfer-tmp/Lex.hs:417:29:
    Couldn't match expected type ‘Bool’ with actual type ‘Int#’
    In the first argument of ‘(&&)’, namely ‘(offset >=# 0#)’
    In the expression: (offset >=# 0#) && (check ==# ord_c)
    In the expression:
      if (offset >=# 0#) && (check ==# ord_c) then
          alexIndexInt16OffAddr alex_table offset
      else
          alexIndexInt16OffAddr alex_deflt s

dist/dist-sandbox-89d2cce8/build/parinfer/parinfer-tmp/Lex.hs:417:48:
    Couldn't match expected type ‘Bool’ with actual type ‘Int#’
    In the second argument of ‘(&&)’, namely ‘(check ==# ord_c)’
    In the expression: (offset >=# 0#) && (check ==# ord_c)
    In the expression:
      if (offset >=# 0#) && (check ==# ord_c) then
          alexIndexInt16OffAddr alex_table offset
      else
          alexIndexInt16OffAddr alex_deflt s
cabal: Error: some packages failed to install:
parconc-examples-0.3.4 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by simonmar** [comment]
I just pushed changes to make it compile with GHC 7.10, although the accelerate and distributed packages don't work yet.

**Comment by apauley** [comment]
Thanks, the book instructions (cabal unpack etc) now works fine with GHC 7.10 on my Mac.
"cabal install" in this git repo still fails for a few executables (parinfer, tmvar etc as mentioned above).

On NixOS with GHC 7.8.3, the cabal unpack instructions fails when trying to build parinfer, saying that alex could not be found. I did a manual "cabal install alex" which successfully completed, but a subsequent build still failed with the same error. I also installed alex with the nix package manager, but this did not help either. In the git repo on this NixOS environment I managed to get past this specific build error by adding alex as a build dependency, and also happy when it failed next for the same reason.

```
$ cabal build

...

Preprocessing executable 'parinfer' for parconc-examples-0.3.5...
cabal: The program 'alex' is required but it could not be found

[andreas@nixos:~/Code/Haskell/tmp/parconc-examples-0.3.5]$ cabal install alex
Resolving dependencies...
Notice: installing into a sandbox located at
/home/andreas/Code/Haskell/tmp/parconc-examples-0.3.5/.cabal-sandbox
Configuring alex-3.1.4...
Building alex-3.1.4...
Installed alex-3.1.4

[andreas@nixos:~/Code/Haskell/tmp/parconc-examples-0.3.5]$ cabal build
Building parconc-examples-0.3.5...
Preprocessing executable 'rpar' for parconc-examples-0.3.5...
Preprocessing executable 'sudoku1' for parconc-examples-0.3.5...
Preprocessing executable 'sudoku2' for parconc-examples-0.3.5...
Preprocessing executable 'sudoku3' for parconc-examples-0.3.5...
Preprocessing executable 'sudoku4' for parconc-examples-0.3.5...
Preprocessing executable 'sudoku5' for parconc-examples-0.3.5...
Preprocessing executable 'strat' for parconc-examples-0.3.5...
Preprocessing executable 'strat2' for parconc-examples-0.3.5...
Preprocessing executable 'strat3' for parconc-examples-0.3.5...
Preprocessing executable 'rsa' for parconc-examples-0.3.5...
Preprocessing executable 'rsa1' for parconc-examples-0.3.5...
Preprocessing executable 'rsa2' for parconc-examples-0.3.5...
Preprocessing executable 'kmeans' for parconc-examples-0.3.5...
Preprocessing executable 'GenSamples' for parconc-examples-0.3.5...
Preprocessing executable 'parmonad' for parconc-examples-0.3.5...
Preprocessing executable 'rsa-pipeline' for parconc-examples-0.3.5...
Preprocessing executable 'fwsparse' for parconc-examples-0.3.5...
Preprocessing executable 'fwsparse1' for parconc-examples-0.3.5...
Preprocessing executable 'timetable' for parconc-examples-0.3.5...
Preprocessing executable 'timetable1' for parconc-examples-0.3.5...
Preprocessing executable 'timetable2' for parconc-examples-0.3.5...
Preprocessing executable 'timetable3' for parconc-examples-0.3.5...
Preprocessing executable 'parinfer' for parconc-examples-0.3.5...
cabal: The program 'alex' is required but it could not be found

[andreas@nixos:~/Code/Haskell/tmp/parconc-examples-0.3.5]$ which alex
/home/andreas/.nix-profile/bin/alex

[andreas@nixos:~/Code/Haskell/tmp/parconc-examples-0.3.5]$ alex --version
Alex version 3.1.3, (c) 2003 Chris Dornan and Simon Marlow

[andreas@nixos:~/Code/Haskell/tmp/parconc-examples-0.3.5]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.8.3
```

**Comment by simonmar** [comment]
I think the build failures are because the version of Alex you have is 
too old for GHC 7.8.4.  cabal install alex and you should be good to go.

Cheers,
Simon
